# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dinner_Mgmt',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_date', models.DateField()),
                ('t_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='launch_Mgmt',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_date', models.DateField()),
                ('t_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tiffin_Mgmt',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_date', models.DateField()),
                ('t_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Mgmt',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=20)),
                ('u_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
